pkgbuild: update expected test failures
mgr is now failing because of...

> module 'OpenSSL.crypto' has no attribute 'X509Req'

in test_tls.py -- probably this is a real error, and I should check more
deeply in the next pkgrel if there's anything I can backport.

(NTS: "mgr_util.py:642: in create_self_signed_cert")

The others remain broken for the same reasons as before